### ISSUE TITLE
Redesign Home Page

### ISSUE THREAD

**Issue by Parthipan-Natkunam** [blastpad/BlastPad-UI-Meta#1]
Making a new design and implementing it for the home page of Blastpad UI website.

**Comment by Parthipan-Natkunam** [comment]
Hi @honeysilvas , I have made a pull request for this issue. Thanks.

**Comment by honeysilvas** [comment]
I accepted the pull request.  The new design looks great.  I love the colors!

**Comment by Parthipan-Natkunam** [comment]
Thanks @honeysilvas .
